title: iphoneten-Blod
description: "iphoneten-Blod"
author:
  name: "iphoneten"
  email: "wowoo74110@gmail.com"
  url: "https://iphoneten.github.io/"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "iphoneten"
year : "2023"
